version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
      user: postgres
    environment:
      CC: clang
      CXX: clang++
  gcc:
    docker:
    - image: fost/circleci
      user: postgres
    environment:
      CC: gcc-10
      CXX: g++-10

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: libraries
          command: |
            git clone git@github.com:hotkit/cord.git .circleci/cord
            git clone git@github.com:hotkit/fost-base.git .circleci/fost-base
            git clone git@github.com:hotkit/fost-beanbag.git .circleci/fost-beanbag
            git clone git@github.com:hotkit/fost-boost.git .circleci/boost
            ln -s /opt/fost-boost/boost .circleci/boost/boost
            git clone git@github.com:hotkit/fost-crypto.git .circleci/crypto
            git clone git@github.com:hotkit/fost-internet.git .circleci/fost-internet
            git clone git@github.com:hotkit/fost-postgres.git .circleci/fost-postgres
            git clone git@github.com:hotkit/fost-web.git .circleci/fost-web
            git clone git@github.com:hotkit/json-schema.git .circleci/json-schema
            git clone git@github.com:hotkit/threading.git .circleci/threading
            git clone git@github.com:jtv/libpqxx.git .circleci/libpqxx
      - run:
          name: cmake
          command: cmake -G Ninja -S .circleci -B .circleci -DCMAKE_BUILD_TYPE=<< parameters.variant >>
      - run:
          name: ninja
          command: ninja -j1 -C .circleci
      - run:
          name: check tests
          command: ninja -j1 -C .circleci check
      - run:
          name: postgres tests
          command: |
            pg_ctlcluster 12 main start
            ninja -j1 -C .circleci pgtest

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]

